baseURL = "http://crossid.io/"
languageCode = "en-us"
title = "CrossID"
theme = "gohugoio"

[social]
twitter = "crossid_io"
linkedin = "10688950"

## Menus

## Global Menu

  [[menu.global]]
    name = "Product Tour"
    weight = 5
    identifier = "product-tour"
    url = "/product-tour/"

  [[menu.global]]
    name = "Docs"
    weight = 1
    identifier = "docs"
    url = "/documentation/"

  # Anything with a weight > 100 gets an external icon
  [[menu.global]]
    name = "GitHub"
    weight = 200
    identifier = "github"
    post = "external"
    url = "https://github.com/crossid"

## Docs

[[menu.docs]]
  name = "About CrossID"
  weight = 1
  identifier = "about"
  url = "/about/"

