baseURL = "http://crossid.io/"
languageCode = "en-us"
title = "CrossID"
theme = "gohugoio"

[social]
twitter = "crossid_io"
linkedin = "10688950"

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true


## As of v0.20, all content files include a default "categories" value that's the same as the section. This was a cheap future-proofing method and should/could be changed accordingly.
[taxonomies]
  category = "categories"

## Menus

## Global Menu

  [[menu.global]]
    name = "Product Tour"
    weight = 5
    identifier = "product-tour"
    url = "/product-tour/"

  [[menu.global]]
    name = "Docs"
    weight = 1
    identifier = "docs"
    url = "/documentation/"

  # Anything with a weight > 100 gets an external icon
  [[menu.global]]
    name = "GitHub"
    weight = 200
    identifier = "github"
    post = "external"
    url = "https://github.com/crossid"

## Footer Contact
  [[menu.footer_contact]]
    name = "Contact Us"
    url = "/contact"

## Docs

[[menu.docs]]
  name = "About CrossID"
  weight = 1
  identifier = "about"
  url = "/about/"

[[menu.docs]]
  name = "SCIM"
  weight = 10
  identifier = "scim"
  url = "/scim/"

[[menu.docs]]
  name = "Enterprise"
  weight = 900
  identifier = "enterprise"
  url = "/enterprise/"
